title: chuhongliang.github.io
subtitle: learn coding, keep coding
link: Homepage link
meta:
  description: Content of description meta tag
  keywords: !!seq
    - keyword1
    - keyword2
    - keyword3
  author: Content of author meta tag
master:
  name: Your name
  about: 一个普通程序员...
  email: Your E-mail
rss:
  title: RSS feed title
  desc: RSS feed description
  lang: zh-cn
  max: 10
copyright:
  owner: Copyrighter
  beginYear: 2019
  endYear: 至今
theme: default
codetheme: night
